name: Downmerge
on:
    workflow_dispatch: {}
jobs:
    prod-to-staging:
        name: Prod to Staging
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions"
            - run: git checkout staging
            - run: git merge origin/production
            - run: git push
    staging-to-dev:
        name: Staging to Dev
        runs-on: ubuntu-latest
        needs: prod-to-staging
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                ref: main
            - name: Fetch staging branch
              run: git fetch origin staging
            - name: Git merge
              run: git merge origin/staging
    notify-engineers:
        name: Notify Engineers of failure
        needs: [prod-to-staging,staging-to-dev]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: prod-to-staging failure
              if: needs.prod-to-staging.result == 'failure'
              run: |
                echo "FROM=Production" >> $GITHUB_ENV
                echo "TO=Staging" >> $GITHUB_ENV
            - name: prod-to-staging failure
              if: needs.staging-to-dev.result == 'failure'
              run: |
                  echo "FROM=Staging" >> $GITHUB_ENV
                  echo "TO=Development" >> $GITHUB_ENV
            - name: Send message to Slack API
              uses: archive/github-actions-slack@v2.8.0
              id: notify
              with:
                slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
                slack-channel: C03GWQ6C89Y
                slack-text: Failed to downmerge ${{ env.FROM }} to ${{ env.TO }}! There are probably merge conflicts, please fix these!
            - name: Result from "Send Message"
              run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
