name: Downmerge
on:
    workflow_dispatch: {}
jobs:
    prod-to-staging:
        name: Prod to Staging
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                ref: staging
            - name: Fetch production branch
              run: git fetch origin production
            - name: Git merge
              run: git merge origin/production
    staging-to-dev:
        name: Staging to Dev
        runs-on: ubuntu-latest
        needs: prod-to-staging
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                ref: main
            - name: Fetch staging branch
              run: git fetch origin staging
            - name: Git merge
              run: git merge origin/staging
    notify-engineers:
        name: Notify Engineers of failure
        needs: [prod-to-staging,staging-to-dev]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: notify
              run: echo "failed"
