name: Pull Request
on:
    pull_request:
        branches: [production, staging]
jobs:
    terraform-fmt:
        name: Terraform Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: hashicorp/setup-terraform@v3
            - id: fmt
              run: terraform fmt -check
